# Generated by Django 4.1.2 on 2022-10-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_location_alter_ad_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
